### ISSUE TITLE
Add FEC on lossy links

### ISSUE THREAD

**Issue by D4rk4** [zehome/MLVPN#110]
Please enhance MLVPN with FEC support like it https://github.com/wangyu-/UDPspeeder

**Comment by sodabrew** [comment]
Have you tried configuring as per https://github.com/wangyu-/UDPspeeder/wiki/UDPspeeder-openvpn-config-guide in order to tunnel traffic from one tool into the other?

**Comment by D4rk4** [comment]
Yes me try, but it can't bind to interface. I think it's not hard to work add FEC to MLVPN, it can bereally useful on lossy link. For example my country has only one crappy uplink and I found, MLVPN link loose about 25% of UDP packets.

**Comment by zehome** [comment]
Sorry, but I will not implement this myself in MLVPN.
