### ISSUE TITLE
MLVPN on Scaleway ARM

### ISSUE THREAD

**Issue by ademar-prothon** [zehome/MLVPN#112]
Hello, and thanks for the work you've already done. 
I wanna ask you if you know how I could optimise your solution for a low cost scaleway, running on 4 ARM cores. Encryption is disabled but I'm still dealing with the half of the bandwidth i expected. 
Thanks for your help and pardon my English ;)

EDIT: Is there a way to get a multi thread version of mlvpn ?

**Comment by zehome** [comment]
when mlvpn is used without encryption, there is not much more overhead other than reading from the kernel and pushing data back to the kernel.

mlvpn is not really designed for very high bandwidth application (100Mbps+) with low cpu power..

I don't think mlvpn can help you in your situation
