### ISSUE TITLE
Release static 64bit version

### ISSUE THREAD

**Issue by lars18th** [zehome/MLVPN#115]
Hi,

The static binary release is great. However, it's 32bit only. So, I suggest to release both 32 and 64 bit versions. The reason is quite simple: in a minimal install of a 64bit system the 32 libraries doesn't exist, threfore a native 64bit static binary is a must have.

I hope you consider it!

**Comment by zehome** [comment]
I'm NOT considering it as static version is a nightmare for security upgrades.

You can build a static version yourself, it's very easy.

Take a look here: https://github.com/zehome/MLVPN/blob/master/.gitlab-ci.yml
