### ISSUE TITLE
Tunnels sections: Add DISABLE option

### ISSUE THREAD

**Issue by lars18th** [zehome/MLVPN#116]
Hi,

To do some tests it will be desirable to have the option to disable a channel in the configuration file:

```
[dsl1]
disable = 1
bindhost = "0.0.0.0"
bindport = 5080
```

So using a simple '#' at start, or changing to '= 0', it will be possible to enable/disable this tunnel.

You agree?

**Comment by zehome** [comment]
What is the benefit over commenting this tunnel + signaling (HUP) the daemon to remove/add the tunnel ?

**Comment by lars18th** [comment]
Hi @zehome ,

> What is the benefit over commenting this tunnel ?

The benefit is changing only one character in the configuration file!

Imagine this scenario: 3 or more tunnels. You are adjusting one to one. So you need to "disable" various and check only one. Then you change to another, etc. But at time this implies to "comment" __all__ lines of the tunnel like:

```
#[dsl1]
#bindhost = "0.0.0.0"
#bindport = 5080
#
# ...
#
```

A lot of work for a lot of lines. But you can do more easy changing only one chracter:

```
[dsl1]
disable = 0
bindhost = "0.0.0.0"
bindport = 5080
```

with 

```
[dsl1]
disable = 1
bindhost = "0.0.0.0"
bindport = 5080
```

I feel it more useable!

**Comment by zehome** [comment]
I'm sorry I won't implement such feature.
