### ISSUE TITLE
Multipath Routing without outside internet

### ISSUE THREAD

**Issue by Div99** [zehome/MLVPN#117]
We have a basic setup, where we have two devices, both connected through 2 LAN networks on 2 different routers. There is no outside internet connection. (IPs are manually assigned, no DHCP)

The example case `Linux with two ADSL uplinks for agregation and failover`, with one device as the client and other as the server is failing as `mlvpn0_updown.sh` is not able to ping `proof.ovh.net` due to lack of internet. We have tried to instead ping one of the client IPs over the LAN networks in `mlvpn0_updown.sh` but it still is not working.

Can you suggest how can we fix this issue? Also, do we need to do any port forwarding to make it work?

**Comment by zehome** [comment]
I'm not sure I understand as mlvpn_updown.sh provided by the package or in the source doesn't do any ping at all

**Comment by zehome** [comment]
I would suggest you try to use the configuration and scripts as installed by the package, not thoses provided in the documentation as examples.
