### ISSUE TITLE
Only One interface/tunnel is used, loadbalance issue

### ISSUE THREAD

**Issue by marc494** [zehome/MLVPN#118]
I compiled MLVPN from source (latest version) both client and the server (Debian 9.6).
In my setup I have a firewall with 2X 20/20 mbps configured. Without MLVPN the total throughput
 is  ~950mbps. 

But when I have both MLVPN tunnels (5080 and 5081) connected, I get only 20mbps at IPERF3. Also when I make a pcap at the MLVPN, I see only the many traffic (the iperf3-test) at port 5080 and at port 5081 a little bit tunnel traffic (2 packets per 2 seconds), but not the iperf3-test.

I have checked both port 5080 and 5081 with a single tunnel and it is working correct, so no routing/firewall issue. It seems a load-balance issue. 

Do I have to change something in my config file?

Both links are connected with the following setup:

![image001](https://user-images.githubusercontent.com/45684792/49642282-e13c9780-fa12-11e8-8abd-22ff884c56d0.png)

Thanks in advance!

[server.txt](https://github.com/zehome/MLVPN/files/2656896/server.txt)
[client.txt](https://github.com/zehome/MLVPN/files/2656920/client.txt)

**Comment by marc494** [comment]
I have change the setting bandwidth_upload, but I get still the same result (20mbps)
I understand that I don´t get gbps speed, but I don´t think 2X 20mbps=40mbps over ethernet is a problem.

**Comment by zehome** [comment]
I don't understand your setup. Why do you want to do multiple tunnels if you have only one eth interface/ip on each side ?

**Comment by marc494** [comment]
I want just test the bandwidth-bundle from client to server.
With a firewall I can control the traffic bandwidth, so I give 20/20 to destination port 5080 (tunnel 1) and 20/20 to tunnel2. Both I need to have 40/40. Because this config is in LAN (LAN-to-LAN) the speed is always the same. When this lan-lan bundel is working I will test it with 4G (which has no fixed speed)

But because the bundel is not working in this test environment, it is not going work in a real-environment.

**Comment by marc494** [comment]
I have also tried with 2 eth-interfaces at the client, but I get the same result (only 20mbps, with both tunnels connected).

**Comment by zehome** [comment]
Try a tcpdump or run with debug mode to get more information on what mlvpn is doing.

It's not going to work with a variable speed 4g link anyway.

**Comment by marc494** [comment]
I have found the issue, it was the option loss_tolerence. But in the documentation I read  ¨If you have a high latency 3G/4G link and a DSL connection, then adjust reorder_buffer_size to a reasonable value to get good performance.¨ Is it possible to have a LAN from 20/20 and one 4G from 70/70 = and have arround  90/90mbps

**Comment by zehome** [comment]
You can try, but I bet you'll get nowere near what you would expect. 4G is constantly changing bandwidth and the static roundrobin used by mlvpn just won't be enough.

**Comment by marc494** [comment]
But when I have the following situation:
LAN: 10/10 (fixed)
WWAN: 30/30 (software fixed)

To what value should I change the  reorder_buffer_size.
And are the more settings I can change to get arround ~40/40mbps as bundle?

**Comment by zehome** [comment]
disable the reorder system to get the best results.

**Comment by marc494** [comment]
I have disabled the system and it is working perfect!
Thanks!
