### ISSUE TITLE
PKI: one server keys + multiple clients keys

### ISSUE THREAD

**Issue by LovingFox** [zehome/MLVPN#122]
Does this project support PKI for secure communications? Like OpenVPN: server instance with server key and multiple client instances each with own key.

**Comment by zehome** [comment]
@LovingFox mlvpn only supports symmetric cryptography. The design is NOT like OpenVPN at all: one client **requires** one server.

**Comment by LovingFox** [comment]
@zehome thanks, I understood

**Comment by zehome** [comment]
exactly right :)
