### ISSUE TITLE
MTU: mtu inside the tunnel

### ISSUE THREAD

**Issue by LovingFox** [zehome/MLVPN#125]
Is it possible to set MTU for the MLVPN-tunnel interface?

For example there is a WAN Ethernet link with MTU 1400. Increasing is impossible. I set tunnel through that WAN. And I need to have possible send and receive packets size 1550 via the tunnel. How can I do it?

Schema:
Host1 --> (1550) lan SERVER1 wan (1400) -- [MLPN-tunnel MTU 1550] -- (1400) wan SERVER2 lan (1550) --> Host2

**Comment by zehome** [comment]
MLVPN does not support fragmentation. You NEED to set the correct MTU on the sending side, by using TCP MSS or using small UDP packets.
