### ISSUE TITLE
packet duplication on mlvpn

### ISSUE THREAD

**Issue by proskater123** [zehome/MLVPN#132]
Does MLVPN support packet duplication yet, and if so, is there a starting spot I can start working with it? We are testing a solution for VoIP, and sending VoIP over several links with the hope that we can keep the call up without any dropped calls. 

Lastly, does MLVPN use ECF, or some other algorithm for packet duplication if it does support it?

**Comment by markfoodyburton** [comment]
My 'fork' (it's deviated too much to call it a fork) of MLVPN does packet duplication and other tricks to TRY and keep the flow of traffic going.
https://github.com/markfoodyburton/ubond
I personally use it to transport all our internet traffic, including voip - but - your millage will vary....

**Comment by proskater123** [comment]
Thanks!! I am going to check it out now.
