### ISSUE TITLE
I want this type topology..

### ISSUE THREAD

**Issue by rishabhsingh2** [zehome/MLVPN#134]
![6](https://user-images.githubusercontent.com/66168205/90109435-73a94880-dd69-11ea-995b-c44310b7b1dd.png)
I want to this type topology so please help me.
How to create mlvpn.conf and mlvpn_updown.sh files and how to run this codes in debian buster. Please help me

**Comment by zehome** [comment]
basically, you don't need to touch mlvpn_updown.sh.

Your schema doesn't make much sense as client and server are on the same "172.16.11.0 and 172.16.12.0" networks

**Comment by zensdw-dev** [comment]
yes it is same networks but what changes is mlvpn.conf file and how to check MLVPN tunnel is create or not

**Comment by rishabhsingh2** [comment]
Yes i know it is same network but what changes needs in mlvpn.conf file and how to check MLVPN tunnel is create or not

**Comment by rishabhsingh2** [comment]
Hi, 
Actually this is dummy lab setup first will be try to MLVPN is work or not in this setup. Then try to main setup. So please help me..

**Comment by rishabhsingh2** [comment]
hi, 
how to cretae mlvpn.conf file please help me..

**Comment by zehome** [comment]
I'm sorry but no, if you don't have any question other than "Please do the work for me", it won't happen.
