### ISSUE TITLE
How to configure multiple spoke location to one mlvpn hub location

### ISSUE THREAD

**Issue by rishabhsingh2** [zehome/MLVPN#138]
![20200825_173046](https://user-images.githubusercontent.com/66168205/91171956-0bf3e580-e6f9-11ea-937a-9a836736b550.png)

How to configure multiple clients to one server with in a same port(like as 5080).

**Comment by rishabhsingh2** [comment]
need a help. please give the suggestion how to implement this type setup.

**Comment by markfoodyburton** [comment]
RTFM - different port per client, different server per tunnel.

**Comment by rishabhsingh2** [comment]
what is RTFM?
it is not possible if server side one configuration file wrote and inside a file both clients data are fill at a time.?

**Comment by rishabhsingh2** [comment]
> RTFM - different port per client, different server per tunnel.

what is RTFM?
it is not possible if server side one configuration file wrote and inside a file both clients data are fill at a time.?

**Comment by zehome** [comment]
I've already responded, sorry
