### ISSUE TITLE
multi-link UPD forwarder without VPN

### ISSUE THREAD

**Issue by CecilioGovain** [zehome/MLVPN#149]
@zehome thanks, I understood 

That's mean if I want make star topology (server is a center and many spokes) I need to run multiple instance of mlvpn daemon on a server side, one per spoke. Every mlvpn daemon will use one personal UDP port. That is right?

_Originally posted by @LovingFox in https://github.com/zehome/MLVPN/issues/122#issuecomment-486175537_

exactly right :)
_Originally posted by @zehome in https://github.com/zehome/MLVPN/issues/122#issuecomment-486271905

**Comment by CecilioGovain** [comment]
If we implement a multi-link UPD tunnel without VPN support, then use this tunnel to connect the OpenVPN server on the same VPS machine, we will get a star topology VPN. OpenVPN has a client to client feature, is is useful for some situations. But OpenVPN has no multi-link support, so we have to combine the two.

**Comment by CecilioGovain** [comment]
A UPD port forwarder with multi-link support and without root privilege, and can run in almost any OS, and make one server config can service multiply clients, it will be easy to use and awesome.
Then let OpenVPN client connect the server through this multi-link UPD port forwarder,  we can build a stable client to client VPN.

**Comment by zehome** [comment]
without root, you can't have a tun/tap interface. MLVPN uses privilege separation for increased security.

The VPN aspect is not mandatory, you can just have host to host communication, just don't setup any routes.

You can use openvpn inside, but you'll have very poor performance.
