### ISSUE TITLE
OpenBSD pledge wroute issue

### ISSUE THREAD

**Issue by rapenne-s** [zehome/MLVPN#152]
When I run mlvpn 2.3.5 on OpenBSD as a client I have a "wroute" error in dmesg due to pledge.

`mlvpn[22534]: pledge "wroute", syscall 105`

Maybe we should add wroute to the pledge list.

**Comment by gpontis** [comment]
After installing mlvpn 2.3.5 package on OpenBSD 6.8, as client I get a sys call error on init:

/bsd: mlvpn[3101]: pledge "init", syscall 105
