### ISSUE TITLE
Tunnels stay offline after a VDSL/Modem reconnection / new external IPs becomes active

### ISSUE THREAD

**Issue by Himan2001** [zehome/MLVPN#154]
There is actualy a Problem when a NAT connection in front is reloaded and got all 24hours a new dynip.

It works with Fritzboxes 7490/7590, but not with Fritzboxes 7581/82 and with Freshtomato when all firewall rules
are cleaned when a new PPPoE Connection is established. Here the running daemons stays permament in offline
state and the tunnel is finaly down.

When the entire mlvpn daemon is cold startet, however all lines are asap up again.
It looks like there are still outdated Session data cached from the provious connection and this is not cleared
cleanly after a tunnel goes down for a few seconds and comes back with a new exteran IP.

I noted that further more when i use some huawei LTE routers and the LTE connection get from time to time
a new external IP. The tunnels here then switch to permanent down. too.

This is not an issue with the Firewall or Modems, it is in MLVPN, because other vpn-daemons have not this issues
when connection is interrupted and the external IP Situation has changed. Maybee after a tunnel down a cleaning
of some used internal session data is needed somewehe in the code ?

It looks like, that the previous used outgoing port is still in used and mlvpn trys to reuse it - but this session data
is longer valid in the NAT table of the Router. 

I trys to used a fixed Sender-Port and with a random Port outgoing in direction of the remote VPN-Server. The result is
always reproducable. Rebooting the Firewall in front or get a new PPPoE-Session with new IP-Set - previous tunnels goes down - and stay down - until a cold start from mlvpn is made. This way a full init is made and i got all Tunnels asap back.

**Comment by zehome** [comment]
Actually, mlvpn does not handle changing ip addresses at all. If you have such a case, you have to reload the daemon for the dns cache to be flushed. Otherwise, that's a router issue I think
