### ISSUE TITLE
SIGHUP signal is provide in mlvpn process . 

### ISSUE THREAD

**Issue by rutul039** [zehome/MLVPN#161]
if i have change the subtunnel(L1R1) parameters in configuration file  then  give the signal SIGHUP(pkill -SIGHUP mlvpn) then all subtunnels (Like [L1R1],[L2R2] etc.) are down and main interface(mlvpn0) are also down.
 why ?

please Give Answer 
Thanks

**Comment by zehome** [comment]
That's the way mlvpn works, contributions are welcome.

**Comment by rutul039** [comment]
hello ,
29-11-2021@17:48:30 [WARN/control] cannot bind socket /usr/local/var/run/mlvpn/mlvpn.sock: No such file or directory

actually i have to create unix socket and give the control_unix_path is  "/usr/local/var/run/mlvpn/mlvpn.sock" this. and mlvpn.sock file is also there this path.

please give answer.
Thanks
