### ISSUE TITLE
MLVPN can't use more than 2 ports at the same time?

### ISSUE THREAD

**Issue by amatus-** [zehome/MLVPN#162]
Hello everyone!
Didn't find an answer in the documentation. Can I have more than 2 connections to the server at the same time? 

```
[link1]
bindhost = "0.0.0.0"
bindport = 6001

[link2]
bindhost = "0.0.0.0"
bindport = 6002

[link3]
bindhost = "0.0.0.0"
bindport = 6003

```
With this configuration, the server only listens on ports 6001 and 6002.

In the logs I see this:

```
mlvpn[64523]: new password set
mlvpn[64523]: link1 tunnel added
mlvpn[64523]: link2 tunnel added
mlvpn[64523]: link3 tunnel added
mlvpn[64523]: created interface `mlvpn0'
mlvpn[64523]: link1 bind to 0.0.0.0
mlvpn[64523]: link2 bind to 0.0.0.0
mlvpn[64523]: link2 new connection -> 111.111.111.111:25895
mlvpn[64523]: link2 authenticated
mlvpn[64523]: link1 new connection -> 111.111.111.111:10636
mlvpn[64523]: link1 authenticated
```

**Comment by amatus-** [comment]
In the logs I see
`link3 getaddrinfo(,0.0.0) failed: Unknown error`

**Comment by zehome** [comment]
```[link3]
bindhost "0.0.0.0"
bindport = 6003
```

Missing =

**Comment by zehome** [comment]
You have to be careful with "0.0.0.0", as mlvpn won't really know what ip address to use to output UDP packets, in case you have source routing enabled. You should specifiy the IP address explicitly

**Comment by amatus-** [comment]
> Missing =

Thank you for your reply. I corrected my typo, but I guess that's not the point.

Now my config is like this
```
[link1]
bindhost = "111.222.333.444"
bindport = 6001

[link2]
bindhost = "111.222.333.444"
bindport = 6002

[link3]
bindport = "111.222.333.444"
bindport = 6003 
```

And an error in the syslog

`mlvpn[7070]: link3 getaddrinfo(,5.188) failed: Unknown error`
