### ISSUE TITLE
Is this project still alive working?

### ISSUE THREAD

**Issue by vwidmer** [zehome/MLVPN#165]
Is this project still alive.. people still using it? I cant seem to get it to work.

**Comment by zehome** [comment]
It is, depends what you want to use it for. Doesn't work for very high bandwidth or unstable networks like 4G

**Comment by kb9gxk** [comment]
> Is this project still alive.. people still using it? I cant seem to get it to work.

I started a new project in rust.

https://GitHub.com/4jpps/mlvpn-rs
