### ISSUE TITLE
Routage

### ISSUE THREAD

**Issue by pr1csynth** [zehome/MLVPN#25]
Bonjour ! 

Je viens de trouver ton soft, je trouve ça juste génial, étant donné que j'ai deux lignes ADSL chez OVH et Free et que nous avons besoin chez nous d'avoir toujours au moins un lien actif.

J'ai déjà réussi à connecter un poste chez moi à mon serveur OVH mais maintenant j'aimerais que ce poste serve de routeur pour tout mon réseau et que tout sorte par le serveur OVH. En lisant tes quelques apparitions sur les forums et commentaires, j'imagine que c'est l'application que tu en fais. Est-ce que tu pourrais m'indiquer comment mettre en place un routage comme celui-ci ? J'ai déjà manipulé les iptables, mais c'était plus de la chance qu'autre choseue ça marche ;D

Merci d'avance !
Antoine.

**Comment by ndarnis** [comment]
Bonjour, 
pour des raisons professionnelles je viens de m'intéresser à MLVPN qui m'a semblé tout à fait correspondre à notre besoin d'améliorer un mauvais débit internet avec un cumul de 2 liens ADSL (ovh: 200 ko/s et free: 400 ko/s). J'espérais avoir du 480 ko/s (200+400-20%) avec MLVPN. Je pense avoir tout bien configuré, avec un serveur chez kimsufi, un client sur une ubuntu 14.04, avoir bien vérifié coté client et coté serveur via tcpdump que les paquets passent bien par les 2 liens, etc. Bref, je n'ai jamais obtenu mieux que 416 ko/s. Cela fait plusieurs jours que j'essaie de comprendre pourquoi, de revoir les configurations, etc. Je sèche complètement, c'est pourquoi je me permets de lancer un appel au secours. 
D'avance, merci infiniement pour votre aide précieuse!

**Comment by flapvhd** [comment]
Bonjour,
C'est le comportement normal de MLVPN de se caler sur le debit le plus bas... 
Tu ne devrais pas pouvoir faire mieux que cela.
A+

**Comment by zehome** [comment]
non c'est pas tout a fais vrai, mais avoir un débit pas terrible sur deux lignes qui sont complètement différentes c'est un comportement normal en effet.


Il est impératif sur cette configuration de paramétrer coté *serveur kimsufi* pour le paramètre bandwidth_upload à par exemple


Ligne OVH: 204800
Ligne Free: 409600

Ceci est obligatoire pour que mlvpn puisse équilibrer l'envoi de données entre les deux lignes (envoyer deux fois plus via free que via ovh)


Aussi attention de bien vérifier que vous utilisez mlvpn 2.X

**Comment by ndarnis** [comment]
Je me doute en effet que ce qu'écrit flapvhd est inexact puisque:
- le débit que j'obtiens est le maximum des 2 connexions et non le minimum comme il l'écrit
- le débit que je devrais obtenir devrait avoisiner 480 ko/s comme l'écrit  zehome dans son commentaire du 5 Nov 2013 : "Le débit décendant devrait au MINIMUM être celui de tes 2 lignes -20%."

J'ai bien noté les remarques de zehome: j'ai modifié la config coté serveur comme indiqué, mais par contre le paquet mlvpn installé est le 1.3.2. J'avais rencontré des difficultés à l'installation de toute autre version. Je vais m'y remettre et reviendrai vers vous si ces modifications ne sont pas concluantes. 
Merci en tout cas de vos réponses si rapides!

**Comment by zehome** [comment]
sincèrement il faut vraiment passer sur 2.X qui est bien meilleure sur beaucoup de points.

**Comment by ndarnis** [comment]
Je vous crois volontiers, mais où la trouver?
Je n'ai trouvé que la version packagée debian 1.3.2 et la version github ici: git clone https://github.com/zehome/MLVPN.git. Or, cette dernière version se lance, mais n'écrit aucun message même avec l'option -v, et les interfaces mlvpn0 coté client et coté serveur ne montent pas. La commande mlvpn -V donne : "mlvpn version ev-04f4da2". Je ne sais donc même pas quelle est cette version.

D'avance, merci.

**Comment by zehome** [comment]
```shell
sudo apt-key adv --keyserver pgp.mit.edu --recv 3324C952
echo "deb http://debian.mlvpn.fr unstable/"
> /etc/apt/sources.list.d/mlvpn.list
sudo apt-get update
sudo apt-get install mlvpn
```

mlvpn version ev-04f4da2 correspond à la toute dernière version disponible.


Si mlvpn ne se lance pas, essayer de lancer à la main:

```
mlvpn --user xxx -c /path/to/mlvpn.conf --debug -vv
```

Remplacer xxx et le chemin vers le fichier de configuration par les bon 
paramètres.


N'oubliez pas de vérifier au besoin /var/log/syslog.

**Comment by ndarnis** [comment]
Merci, mais la procédure que vous indiquez pour installer le paquet debian est exactement celle que j'ai utilisée, mais j'obtiens ainsi la version 1.3.2... Je vais donc continuer à tester la version obtenue via github: la ev-04f4da2. J'ai rajouté les options --debug et -vv et j'obtiens:
2015-06-29T09:15:12 [ DBG] absolute maximum mtu: 1456
2015-06-29T09:15:12 [INFO/config] free tunnel added
2015-06-29T09:15:12 [INFO] free bind to any
2015-06-29T09:15:12 [WARN] free bind error: Invalid argument
2015-06-29T09:15:12 [WARN] free bind error
2015-06-29T09:15:12 [INFO/config] ovh tunnel added
2015-06-29T09:15:12 [INFO] ovh bind to any
2015-06-29T09:15:12 [WARN] ovh bind error: Invalid argument
2015-06-29T09:15:12 [WARN] ovh bind error
2015-06-29T09:15:12 [INFO] created interface `mlvpn0'
2015-06-29T09:15:12 [ DBG/wrr] ovh weight = 33.333333 (204800 614400)
2015-06-29T09:15:12 [ DBG/wrr] free weight = 66.666667 (409600 614400)
Il semble donc y avoir un soucis...

**Comment by zehome** [comment]
> 2015-06-29T09:15:12 [INFO] free bind to any
> 2015-06-29T09:15:12 [WARN] free bind error: Invalid argument
> 2015-06-29T09:15:12 [WARN] free bind error


Faites voir la configuration

**Comment by ndarnis** [comment]
Coté serveur avec la version ev-04f4da2, /var/log/syslog ne contient aucune info concernant mlvpn.
Config utilisée (et qui fonctionne avec la version 1.3.2): 

[general]
statuscommand = "/etc/mlvpn/mlvpn0_updown.sh"
tuntap = "tun"
loglevel = 4
mode = "server"
protocol = "udp"
interface_name = "mlvpn0"
timeout = 30
password = "toto"
#cleartext_data = 1

[free]
bindport = 5080
bandwidth_upload = 409600
bandwidth_download = 512000
#latency_increase = 40

[ovh]
bindport = 5081
bandwidth_upload = 204800
bandwidth_download = 512000

**Comment by zehome** [comment]
bindhost = "0.0.0.0"


Pour info l'interface ne montera PAS tant que mlvpn ne
peut pas monter un tunnel avec l'autre coté.

**Comment by ndarnis** [comment]
Bonjour, j'ai rajouté la ligne bindhost à la config coté serveur, mais je ne vois pas vraiment de différence:
2015-06-30T07:22:03 [ DBG] absolute maximum mtu: 1456
2015-06-30T07:22:03 [INFO/config] free tunnel added
2015-06-30T07:22:03 [INFO] free bind to any
2015-06-30T07:22:03 [WARN] free bind error: Invalid argument
2015-06-30T07:22:03 [WARN] free bind error
2015-06-30T07:22:03 [INFO/config] ovh tunnel added
2015-06-30T07:22:03 [INFO] ovh bind to any
2015-06-30T07:22:03 [WARN] ovh bind error: Invalid argument
2015-06-30T07:22:03 [WARN] ovh bind error
2015-06-30T07:22:03 [INFO] created interface `mlvpn0'
2015-06-30T07:22:03 [ DBG/wrr] ovh weight = 33.333333 (204800 614400)
2015-06-30T07:22:03 [ DBG/wrr] free weight = 66.666667 (409600 614400)
J'ai installé la même version coté client, je l'ai lancé, j'ai des affichages en permance, mais toujours pas d'interface mlvpn0 ni coté client, ni coté serveur.

**Comment by ndarnis** [comment]
Toutes mes confuses, j'ai découvert que la directive bindhost = "0.0.0.0" devait être mise dans les sections [ovh] et [free]. Les logs sont mieux coté serveur:
2015-06-30T08:01:42 [ DBG] absolute maximum mtu: 1456
2015-06-30T08:01:42 [INFO/config] free tunnel added
2015-06-30T08:01:42 [INFO] free bind to 0.0.0.0
2015-06-30T08:01:42 [INFO/config] ovh tunnel added
2015-06-30T08:01:42 [INFO] ovh bind to 0.0.0.0
2015-06-30T08:01:42 [INFO] created interface `mlvpn0'
2015-06-30T08:01:42 [ DBG/wrr] ovh weight = 33.333333 (204800 614400)
2015-06-30T08:01:42 [ DBG/wrr] free weight = 66.666667 (409600 614400)
Mais toujours aucune interface mlvpn0 de montée des 2 cotés.

**Comment by ndarnis** [comment]
Du coup, je vais tout re-vérifier, voire tout ré-installer proprement de mon coté, il y a peut-être un soucis avec des lib dépendantes (libev, libsodium, etc). Je reviendrai ensuite vers vous si le problème persiste et/ou si les perfs sont mauvaises. Merci encore de votre aide et de votre réactivité.

**Comment by zehome** [comment]
non mais l'interface ne monte *QUE* après que tunnel soit opérationel.

Ces logs sont incomplets, je ne voit aucune tentative de connexion
ni aucune réception de connexion.


rajouter les info debug protocole et reseau:


-vv --debug -Dprotocol -Dnet

**Comment by ndarnis** [comment]
OK, trouvé une partie du dernier soucis: agent d'entretien qui a du s'entraver (entre hier et ce matin) dans cable réseau, languette cassée, cable qui se débranchait tout seul... Avec un cable neuf, j'ai une connexion OK des 2 cotés, l'interface mlvpn0 monte bien, mais pas de ping possible des ips des interfaces entre elles:
coté serveur
mlvpn0          inet addr:10.42.42.1
coté client:
mlvpn0          inet addr:10.42.42.2
Sur le serveur, ping 10.42.42.1 ok, mais ping 10.42.42.2 ko.
C'est l'inverse sur le client.
Tout ceci fonctionne avec la version 1.3.2 sans rien changer d'autre (j'ai pris le temps de le retester).

**Comment by zehome** [comment]
On 30/06/2015 10:54, ndarnis wrote:
> Sur le serveur, ping 10.42.42.1 ok, mais ping 10.42.42.2 ko.

=> Mauvaise table de routage

**Comment by zehome** [comment]
On 30/06/2015 10:54, ndarnis wrote:
> Sur le serveur, ping 10.42.42.1 ok, mais ping 10.42.42.2 ko.

Soucis firewall?

**Comment by ndarnis** [comment]
Coté serveur:
default via 37.187.2.254 dev eth0  metric 100 
10.42.42.0/30 dev mlvpn0  proto kernel  scope link  src 10.42.42.1 
37.187.2.0/24 dev eth0  proto kernel  scope link  src 37.187.2.13 
192.168.2.0/24 via 10.42.42.2 dev mlvpn0 

target     prot opt source               destination         
MASQUERADE  all  --  anywhere             anywhere            
MASQUERADE  all  --  10.42.42.0/30        anywhere            
MASQUERADE  all  --  192.168.2.0/24       anywhere

Coté client:
default via 10.42.42.2 dev mlvpn0  scope link 
10.42.42.0/30 dev mlvpn0  proto kernel  scope link  src 10.42.42.2 
192.168.0.0/24 dev eth0  proto kernel  scope link  src 192.168.0.1 
192.168.1.0/24 dev eth0  proto kernel  scope link  src 192.168.1.1 
192.168.2.0/24 dev eth1  proto kernel  scope link  src 192.168.2.1

**Comment by ndarnis** [comment]
Voyez-vous un soucis ou souhaitez-vous que je vous copie/colle d'autres infos?
D'avance, merci.

**Comment by ndarnis** [comment]
Bonjour, je confirme ce que je disais précédemment. Je viens d'installer la version 1.3.2 sur un nouveau serveur ubuntu 14.04 tout fraichement installé:
echo "deb http://debian.mlvpn.fr mlvpn-unstable/" >/etc/apt/sources.list.d/mlvpn.list
sudo apt-key adv --keyserver pgp.mit.edu --recv 3324C952
sudo apt-get update
sudo apt-get install mlvpn
J'ai fait de même sur la machine cliente.
Je lance mlvpn de chaque coté: les interfaces mlvpn0 montent de chaque coté, le ping 10.42.42.1 et 10.42.42.2 fonctionnent depuis chaque extrémité. Tout fonctionne, excepté les débits qui sont, on l'a vu décevant. Puis, j'ai désinstallé le paquet mlvpn 1.3.2 pour la remplacer par la dernière version sur chaque machine:
git clone https://github.com/zehome/MLVPN.git
cd MLVPN
./autogen.sh
./configure
make
make install
J'ai lancé de chaque coté mlvpn, et je retombe sur le dernier soucis: pas de ping croisé! Je n'ai absolument rien changé dans les configs, ni dans les tables de routage ni dans iptables. Je ne comprends pas pourquoi il y a cette différence et qui de plus me semble bien liée à mlvpn.
Qu'en pensez-vous?
D'avance, merci.

**Comment by zehome** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

non ce n'est pas un problème mlvpn, mais un problème dans votre
configuration.



Je ne peux pas faire grand chose sans avoir accès a la machine pour
savoir ce que vous avez fait.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVnPN9AAoJEEC38JAzJMlSUfYIAJzEu291bvLDcNk7vr5flMAc
2DjC9ZCdNjAuskgBsIJnwiROQmKlTH0UAE4ZsFBUOvnnQrG6G735QHrVdMAiY217
SZbCQlxTtTx2ByRmfsdrD+th5Cs5+o3Wss0GU5ZOeykaKKoYch1asvDdWlgk0Hry
j1EkAsV/LcDd+1+GTCruNiSYK8Em+Dx5+RZdQeVT0WkuzucQqXhRmTfw4+lqsI+F
sjWN9lc6TUs9PWceh2Cc7KAX0VnZieEXQSXtwuaPprWO09WKm1VAJ5pLRoOH8/Mq
UFLaSad7iERzLxfwaZkh/9PZQLAhq35fi2CXr/mUuoww0yIrvGlosKbV5re9Xr4=
=Ma8W
-----END PGP SIGNATURE-----

**Comment by ndarnis** [comment]
Y'a t'il des fichiers de configs et/ou des résultats de commandes que je pourrais vous coller ici/ailleurs afin que vous puissiez m'aiguiller? J'ai vraiment besoin de tester votre solution rapidement avant de décider si je peux me baser dessus ou non.
Merci d'avance.

**Comment by zehome** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1



Donnez moi accès temporairement a l'installation via SSH:


ssh-rsa
AAAAB3NzaC1yc2EAAAABIwAAAQEAt523ihiUh3cUddFoSNhCk29P8VBSBYEhfavF/ZSQD7s3mVtMKhFBeDR14LoKMkKhBF39BmhNszC59mNCHv6dw7VHJ6TctdtH5cALpKbNqCCop1LL9kWSIw55nLmJBKe+hSk70BxfHlsKD4hB90ELJIpgeXgBGkUZvd56w0kCzD0K6p2y83t1BL0f6t95QffIWxPr1bZPVdLgI+pJvd07ujEPWPiuJ1V7LRszYWrVXEw1UVWtTd42JZDbcf0hdsKqJBHSflpIQJJHnCyPuZpImgskgNzdcWx5dp4AkkTB7RNulSqTlgH4jOUvRKjQc0xRAI0LtzGzSjpYWMaTbV3Syw==
ed@equinoxe

Comme ça en aveugle c'est difficile de diagnostiquer.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVpiKIAAoJEEC38JAzJMlS9dsIAJuiHwJb1Tm0Z8OOdJMXPAU8
Me/2VtOOOCJsc0zbzEyTJajSG+vcKyhrG8LEyGczfk0zb1R1TQ4kP34imemAoIjB
wa7qF1qCHMF6z4IqQey/MO3spHdW9pqxaOa7y2r7UBC8j2czyadH0mj9qNRm2JXd
mCQifXGeWxxO5mwSfZLxBHcblmylAt4B4kWm4ntuFcyxmgaf8dDsdW3uzzIUX1m2
9rri3D7ZfUUYmBVZw7HUjiOcqmKNO564vB/w8+PfOezrGQN4yMtqF+ttAPY8/soK
7VW+NVALqeTPbr+BPTEa8C6/3vmtrikUxmtTAHe6V6w021tWPY/dC224t4o4o6Y=
=gk04
-----END PGP SIGNATURE-----

**Comment by ndarnis** [comment]
Cette adresse est toujours valable: ed@zehome.com ?

**Comment by zehome** [comment]
oui
