### ISSUE TITLE
mlvpn [priv] : unable to chroot: No such file or directory

### ISSUE THREAD

**Issue by rptx** [zehome/MLVPN#31]
Lorsqu'on essaie de démarrer mlvpn via la commande suivante : 
mlvpn --user mlvpn -c /etc/mlvpn/mlvpn0.conf
le message suivant apparait :
mlvpn [priv] : unable to chroot: No such file or directory
Cela est du au fait que le répertoire nécessaire /var/run/mlvpn est effacé à chaque redémarrage de la machine.
Si l'on crée le répertoire avant de lancer la commande, mlvpn démarre.

**Comment by tabbertmj** [comment]
This seems to be back with 2.3.x
