### ISSUE TITLE
Error binding socket mlvpn.sock: Permission denied

### ISSUE THREAD

**Issue by oza4h07** [zehome/MLVPN#36]
I'm trying MLVPN for the first time.

After issuing "mlvpn --user mlvpn -c /etc/mlvpn/mlvpn0.conf" on client,  I'm seeing this in log files (Debian wheezy from repo):
[16:29:13][mlvpn.c:1465] Created tap interface mlvpn0
[16:29:13][control.c:114] Error binding socket mlvpn.sock: Permission denied
[16:29:13][mlvpn.c:320] Binding socket 6 to 192.168.64.13

Trying to reproduce provided example, I can't successfully ping proof.ovh.net.

Could it be possible to elaborate a bit further "Error binding socket mlvpn.sock: Permission denied", indicating for instance which resource is denying acces and which user is denied access ?

Changing /run/mlvpn ownership to mlvpn:root removes this error message.

**Comment by zehome** [comment]
socket path can be configured in the configuration file.
