### ISSUE TITLE
securité dans mlpvn

### ISSUE THREAD

**Issue by bzh35** [zehome/MLVPN#39]
Bonjour,

Serait-ce envisageable d'ajouter lors de l'initialisation de la connexion, une authentification (par clé par exemple).

Le soucis, lorsque l'on a pas d'ip fixe, est que l'on doit laisser ouvert le port ouvert sans filtrage possible, et du coup n'importe qui peut s'y connecter.
De même, si une connexion est déjà initialisée, et que l'on tente depuis un autre serveur de se connecter, mlvpn serveur accepte la connexion (et cela crée des reconnections permanentes..)

**Comment by bzh35** [comment]
Hello,
Je suis actuellement en cours de test sur la nouvelle version.
libsodium pose soucis, il serait bien d'indiquer la version a utiliser pour la compilation (j'ai utilisé la version 1.0.0).

tcpdump montre bien que c'est chiffré, impécable ;)

Par contre j'ai une autre question, qui n'a pas vraiment a voir avec MLVPN, mais comme tu es doué en réseau tu vas surement pouvoir me renseigner.
J'ai modifié ma manière d'utiliser MLVPN, car il est installé sur un serveur seul. J'ai donc :
Serveur internet
      eth0 ip public
      mlvpn0 10.42.42.1
             |
             |
             |
             V
Serveur MLVPN
    eth1:adsl1
    eth1:adsl2
    mlvpn0 10.42.42.2
    eth0 192.168.0.254 (carte reliée sur le réseau /24)

Ce que j'essaie, c'est d'ouvrir le 3306 et de le rediriger sur le 192.168.0.5.
Le seul soucis que j'ai (je pense que c'est le seul car je sais rediriger un port), c'est que un 
ping -I10.42.42.2 192.168.0.5 ne réponds pas. La seule ip que j'arrive a pinger est la .254, logique...

pourrais tu me dire quelle ligne iptables pourrait permettre a 10.42.42.2 de pinger / acceder a 192.168.0.0/24 ?

Bon boulot en tout cas.

ps: j'ai du passer le mss a 1300 sinon j'ai plein de sites qui ne répondent pas

**Comment by zehome** [comment]
salut, j'ai pas compris ce que tu demande.

**Comment by bzh35** [comment]
j'essaie que 10.42.42.2 puisse acceder à 192.168.0.0/24, afin de pouvoir router le port 3306 sur une ip du réseau
