### ISSUE TITLE
 [CRIT/config] file is group/other accessible

### ISSUE THREAD

**Issue by mhand201** [zehome/MLVPN#48]
Bonjour,

Lorsque je lance mlvpn avec la line de command:
mlvpn --user mlvpn -c /etc/mlvpn/mlvpn0.conf

je recois le message d'erreur suivant:
2015-05-13T04:29:57 [CRIT/config] file is group/other accessible. Fix permissions

- OS: debian 8, 64 bit
- Permissions de /etc/mlvpn/*.sh (chmod 700 owned by root)

Merci

**Comment by zehome** [comment]
```ls -l /etc/mlvpn/*
chmod 600 /etc/mlvpn/*.conf
chmod 700 /etc/mlvpn/*.sh
```

**Comment by mhand201** [comment]
Merci ca régler le probleme mais j'ai un autre:
May 14 23:42:46 mlpvn mlvpn[904]: bind port is mandatory in server mode.
May 14 23:42:46 mlpvn mlvpn[904]: Will quit with exit code 1
May 14 23:42:46 mlpvn systemd[1]: mlvpn@mlvpn0.service: main process exited, code=exited, status=1/FAILURE
May 14 23:42:46 mlpvn systemd[1]: Unit mlvpn@mlvpn0.service entered failed state.
May 14 23:42:46 mlpvn systemd[1]: mlvpn@mlvpn0.service start request repeated too quickly, refusing to start.
May 14 23:42:46 mlpvn systemd[1]: Failed to start MLVPN connection to mlvpn0.
May 14 23:42:46 mlpvn systemd[1]: Unit mlvpn@mlvpn0.service entered failed state.

voici le fichier mlvpn0.conf:

[general]
statuscommand = "/etc/mlvpn/mlvpn0_updown.sh"
tuntap = "tun"
loglevel = 4
mode = "server"
protocol = "udp"
interface_name = "mlvpn0"
timeout = 30
password = "pleasechangeme!"

[adsl1]
bindport = 5081
bandwidth_upload = 61440
bandwidth_download = 512000

[adsl2]
bindport = 5082
bandwidth_upload = 61440
bandwidth_download = 512000

**Comment by freemangl** [comment]
> ```shell
> chmod 700 /etc/mlvpn/*.sh
> ```

root@ubcloud:~# ls -l /etc/mlvpn/*
-rw------- 1 root root 261 Jul 31 11:57 /etc/mlvpn/mlvpn0.conf
-rwx------ 1 root root 677 Jul 31 12:04 /etc/mlvpn/mlvpn0_updown.sh
root@ubcloud:~# chmod 600 /etc/mlvpn/*.conf
root@ubcloud:~# chmod 700 /etc/mlvpn/*.sh
root@ubcloud:~# mlvpn --user mlvpn -c /etc/mlvpn/mlvpn0.conf
2020-07-31T12:36:21 [CRIT/fatal] you are not allowed to run this program as root. please specify a valid user with --user option

any ideas? thanks
