### ISSUE TITLE
Latency_increase sur le code actuel

### ISSUE THREAD

**Issue by lastmikoi** [zehome/MLVPN#50]
Bonjour,

J'ai récemment mis en place un setup de mlvpn (freebox+bbox) chez moi, et ça "fonctionne", j'ai toutefois pas mal de problèmes notemment vis à vis des connexions en HTTPS, et je pense que ça a un lien avec la différence de 20ms entre ces deux liens.

La documentation readthedocs parle du setting `latency_increase`, qui semble avoir disparu de la documentation et du code source depuis la version 2.

La gestion de la jigue est elle devenue automatisée? Si non quel settings faut-il utiliser?

**Comment by zehome** [comment]
non latency_increase a été supprimé car inefficace. Le nouveau système de re-ordonnancement devrait éliminer le besoin, avec une solution qui fonctionne.

Voir la branche reorder.

**Comment by zehome** [comment]
Merci pour l'information, j'ai corrigé la documentation
