### ISSUE TITLE
Integration with systemd

### ISSUE THREAD

**Issue by oza4h07** [zehome/MLVPN#52]
Hi,
For me, using an /etc/default/mlvpn file to which config files to read at startup is very convenient idea.

When playing with MLVPN on a Debian Jessie systemd enabled box, I had to type a "systemctl enable mlvpn" command to have MLVPN started at boot time.

Does it make sense to integrate this systemctl command within MLVPN installation script ?
Regards

**Comment by zehome** [comment]
doing **systemctl enable mlvpn** is mandatory when using systemd system.

mlvpn uses systemd generators, like openvpn do to handle multiple configuration file: **systemctl enable mlvpn@configname**

This is pretty much the same as OpenVPN does.
/etc/default/ is a thing of the past it seams. Feel free to point to me other packages doing what you think is better
