### ISSUE TITLE
mlvpn didn't detach from terminal by default

### ISSUE THREAD

**Issue by ocochard** [zehome/MLVPN#67]
mlvpn on FreeBSD didn't detach from terminal:

`[root@router]# mlvpn -c /usr/local/etc/mlvpn/mlvpn.conf -u mlvpn`

=> start correctly but didn't give terminal back

Is a normal behavior ?

**Comment by zehome** [comment]
Yes it's normal. mlvpn dies not have daemoning support. (It's hard ans challenging to do properly)

**Comment by ocochard** [comment]
ok, I will use [daemon(8)](https://www.freebsd.org/cgi/man.cgi?query=daemon) for managing it them.
