### ISSUE TITLE
[FR] MLVPN pour agréger des liens fibres à 100 Mbps?

### ISSUE THREAD

**Issue by flapvhd** [zehome/MLVPN#76]
Bonjour Laurent et tous,

Laurent, est ce que tu penses que MLVPN pourrait s'en tirer correctement si on lui demandait d'agréger 3 accès fibres à 100 Mbps, pris chez le même opérateur? 
Bien sur, les machines impliquées des 2 côtés du tunnel seraient correctement dimensionnées...

J'utilise encore une ancienne version de MLVPN, en secours pour "Viviers Fibre" sur 2 accès adsl et ça marche nickel ;-)

Merci pour ton boulot!

**Comment by zehome** [comment]
Si la crypto est désactivée, je ne voit pas pourquoi cela ne fonctionnerait pas. Cependant à ce type de débit, peut être que MLVPN n'est pas la meilleure solution disponible?
