### ISSUE TITLE
Cannot connect to some HTTPS sites when using MLVPN

### ISSUE THREAD

**Issue by fernandonunez** [zehome/MLVPN#89]
Hi!
First of all I would like to say thanks for you work on this. I think it is a very interesting solution!

I have implemented a test environment but when I establish the MLVPN session I cannot access some HTTPS sites (as github.com) but I can access some others (like google.com).

When I connect a client to the server and I do not use MLVPN I can access the sites just fine.

Network diagram:
![image](https://cloud.githubusercontent.com/assets/23552737/20428203/c1a02af4-ad7f-11e6-9e07-3c7481c75f09.png)

-Laptop 1 connecting to the internet via MLVPN server using a MLVPN tunnel cannot access github.com (but can ping it)
-Laptop2 connecting to the internet via MLVPN server just routing can access github.com

I do not know if you have seen something like that before but it sound weird to me!

Thanks!

**Comment by zehome** [comment]
I think you have an MTU problem.

You must either adjust the mtu on the tunnel and/or adjust the MSS of TCP packets (using iptables for example)

In your "updown.sh" script, you can use:

```
/sbin/iptables -A POSTROUTING -t mangle -p tcp --tcp-flags SYN,RST SYN -o $DEVICE -j TCPMSS --set-mss 1350
```

**Comment by fernandonunez** [comment]
Thanks so much, that was the case indeed!
