### ISSUE TITLE
OpenWRT package

### ISSUE THREAD

**Issue by JuniorJPDJ** [zehome/MLVPN#90]
Hi, can you create openwrt package?

**Comment by zehome** [comment]
No, sorry.

**Comment by azuwis** [comment]
FYI, I've create a pull request to openwrt packages github repo to add mlvpn. https://github.com/openwrt/packages/pull/4271

**Comment by JuniorJPDJ** [comment]
@azuwis You better pull it to LEDE repository ;P
Openwrt is dead now

**Comment by azuwis** [comment]
@JuniorJPDJ The packages feed for LEDE and Openwrt is the some, https://git.lede-project.org/?p=feed/packages.git;a=summary is just a mirror.

The package will be available for both LEDE and Openwrt after the pull request got merged :)
