### ISSUE TITLE
use of wlen

### ISSUE THREAD

**Issue by markfoodyburton** [zehome/MLVPN#92]
Looks to me like the code around
https://github.com/zehome/MLVPN/blob/master/src/mlvpn.c#L550
should be using the pkt->len, not the wlen?
Looks to me like, worst case, this could cause memory corruptions (though, at a guess, we never see it because typically the MTU is set low enough?)

Cheers
Mark.

**Comment by zehome** [comment]
HMm, seems you are right

**Comment by markfoodyburton** [comment]
I can try and clean my tree up, and get some patches to you, but it may take a while...

**Comment by zehome** [comment]
I'll address that issue
